# Generated by Django 6.0.6 on 2026-06-17 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_text', models.TextField(blank=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('current_turn', models.PositiveIntegerField(default=1)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('study_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_session', to='learning.studysession')),
            ],
        ),
        migrations.CreateModel(
            name='LessonTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('teacher_task', models.TextField()),
                ('student_answer', models.TextField(blank=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('correction', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('encouragement', models.TextField(blank=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='agents.lessonsession')),
            ],
            options={
                'ordering': ['turn_number', 'id'],
                'unique_together': {('session', 'turn_number')},
            },
        ),
    ]
