# Generated by Django 6.0.6 on 2026-06-22 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_lessonturn_target_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceDiagnosticSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=32)),
                ('pronunciation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('listening_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('speaking_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recommended_focus', models.CharField(blank=True, default='', max_length=64)),
                ('summary', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_diagnostic_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VoiceDiagnosticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('Pronunciation', 'Pronunciation'), ('Listening', 'Listening'), ('Speaking', 'Speaking')], max_length=64)),
                ('item_number', models.PositiveIntegerField()),
                ('task_type', models.CharField(blank=True, default='', max_length=64)),
                ('prompt_text', models.TextField(blank=True, default='')),
                ('target_text', models.TextField(blank=True, default='')),
                ('passage_text', models.TextField(blank=True, default='')),
                ('question_text', models.TextField(blank=True, default='')),
                ('expected_answer', models.TextField(blank=True, default='')),
                ('user_answer', models.TextField(blank=True, default='')),
                ('transcript', models.TextField(blank=True, default='')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agents.voicediagnosticsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'unique_together': {('session', 'skill', 'item_number')},
            },
        ),
    ]
