# Generated by Django 6.0.6 on 2026-06-23 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_voicediagnosticsession_voicediagnosticitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('target_skill', models.CharField(choices=[('speaking', 'Speaking'), ('listening', 'Listening'), ('pronunciation', 'Pronunciation'), ('general', 'General')], default='speaking', max_length=50)),
                ('cefr_level', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('final_feedback', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_conversation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VoiceConversationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('user_transcript', models.TextField(blank=True, default='')),
                ('ai_response_text', models.TextField(blank=True, default='')),
                ('user_audio', models.FileField(blank=True, null=True, upload_to='voice-conversation/user-audio/')),
                ('ai_audio', models.FileField(blank=True, null=True, upload_to='voice-conversation/ai-audio/')),
                ('transcript_source', models.CharField(choices=[('manual', 'Manual'), ('deepgram', 'Deepgram'), ('fallback', 'Fallback')], default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='agents.voiceconversationsession')),
            ],
            options={
                'ordering': ['session_id', 'turn_number', 'id'],
                'constraints': [models.UniqueConstraint(fields=('session', 'turn_number'), name='unique_voice_conversation_turn_number')],
            },
        ),
    ]
