from django.urls import path

from .views import (
    CoachSummaryView,
    CurriculumRecommendationView,
    DiagnosticEvaluateView,
    ListeningTeacherSessionAnswerView,
    ListeningTeacherSessionDetailView,
    ListeningTeacherSessionStartView,
    PronunciationTeacherSessionAnswerView,
    PronunciationTeacherSessionDetailView,
    PronunciationTeacherSessionStartView,
    SchedulerGeneratePlanView,
    SpeakingTeacherSessionAnswerView,
    SpeakingTeacherSessionDetailView,
    SpeakingTeacherSessionStartView,
    TeacherSessionAnswerView,
    TeacherSessionDetailView,
    TeacherSessionStartView,
    TeacherFeedbackView,
    TeacherSessionView,
    VoiceConversationSessionDetailView,
    VoiceConversationSessionEndView,
    VoiceConversationSessionListView,
    VoiceConversationSessionStartView,
    VoiceConversationTurnCreateView,
)
from .voice_views import (
    ListeningEvaluateBatchView,
    ListeningEvaluateView,
    PronunciationEvaluateView,
    PronunciationEvaluateBatchView,
    SpeakingEvaluateBatchView,
    SpeakingEvaluateView,
    VoiceDiagnosticSessionDetailView,
    VoiceDiagnosticSessionListView,
    VoiceDiagnosticSessionReportView,
    VoiceDiagnosticSessionStartView,
    VoiceDiagnosticPromptsView,
    VoiceDiagnosticTTSView,
)


urlpatterns = [
    path(
        'diagnostic/evaluate/',
        DiagnosticEvaluateView.as_view(),
        name='diagnostic-evaluate',
    ),
    path(
        'curriculum/recommendation/',
        CurriculumRecommendationView.as_view(),
        name='curriculum-recommendation',
    ),
    path(
        'teacher/session/',
        TeacherSessionView.as_view(),
        name='teacher-session',
    ),
    path(
        'teacher/session/start/',
        TeacherSessionStartView.as_view(),
        name='teacher-session-start',
    ),
    path(
        'teacher/session/answer/',
        TeacherSessionAnswerView.as_view(),
        name='teacher-session-answer',
    ),
    path(
        'teacher/session/<int:session_id>/',
        TeacherSessionDetailView.as_view(),
        name='teacher-session-detail',
    ),
    path(
        'teacher/feedback/',
        TeacherFeedbackView.as_view(),
        name='teacher-feedback',
    ),
    path(
        'teacher/speaking/sessions/start/',
        SpeakingTeacherSessionStartView.as_view(),
        name='teacher-speaking-session-start',
    ),
    path(
        'teacher/speaking/sessions/<int:session_id>/',
        SpeakingTeacherSessionDetailView.as_view(),
        name='teacher-speaking-session-detail',
    ),
    path(
        'teacher/speaking/sessions/<int:session_id>/answer/',
        SpeakingTeacherSessionAnswerView.as_view(),
        name='teacher-speaking-session-answer',
    ),
    path(
        'teacher/listening/sessions/start/',
        ListeningTeacherSessionStartView.as_view(),
        name='teacher-listening-session-start',
    ),
    path(
        'teacher/listening/sessions/<int:session_id>/',
        ListeningTeacherSessionDetailView.as_view(),
        name='teacher-listening-session-detail',
    ),
    path(
        'teacher/listening/sessions/<int:session_id>/answer/',
        ListeningTeacherSessionAnswerView.as_view(),
        name='teacher-listening-session-answer',
    ),
    path(
        'teacher/pronunciation/sessions/start/',
        PronunciationTeacherSessionStartView.as_view(),
        name='teacher-pronunciation-session-start',
    ),
    path(
        'teacher/pronunciation/sessions/<int:session_id>/',
        PronunciationTeacherSessionDetailView.as_view(),
        name='teacher-pronunciation-session-detail',
    ),
    path(
        'teacher/pronunciation/sessions/<int:session_id>/answer/',
        PronunciationTeacherSessionAnswerView.as_view(),
        name='teacher-pronunciation-session-answer',
    ),
    path(
        'scheduler/generate-plan/',
        SchedulerGeneratePlanView.as_view(),
        name='scheduler-generate-plan',
    ),
    path(
        'coach/summary/',
        CoachSummaryView.as_view(),
        name='coach-summary',
    ),
    path(
        'voice-diagnostic/prompts/',
        VoiceDiagnosticPromptsView.as_view(),
        name='voice-diagnostic-prompts',
    ),
    path(
        'voice-diagnostic/tts/',
        VoiceDiagnosticTTSView.as_view(),
        name='voice-diagnostic-tts',
    ),
    path(
        'voice-diagnostic/sessions/start/',
        VoiceDiagnosticSessionStartView.as_view(),
        name='voice-diagnostic-session-start',
    ),
    path(
        'voice-diagnostic/sessions/',
        VoiceDiagnosticSessionListView.as_view(),
        name='voice-diagnostic-session-list',
    ),
    path(
        'voice-diagnostic/sessions/<int:session_id>/',
        VoiceDiagnosticSessionDetailView.as_view(),
        name='voice-diagnostic-session-detail',
    ),
    path(
        'voice-diagnostic/sessions/<int:session_id>/report/',
        VoiceDiagnosticSessionReportView.as_view(),
        name='voice-diagnostic-session-report',
    ),
    path(
        'voice-diagnostic/pronunciation/evaluate/',
        PronunciationEvaluateView.as_view(),
        name='voice-diagnostic-pronunciation-evaluate',
    ),
    path(
        'voice-diagnostic/pronunciation/evaluate-batch/',
        PronunciationEvaluateBatchView.as_view(),
        name='voice-diagnostic-pronunciation-evaluate-batch',
    ),
    path(
        'voice-diagnostic/listening/evaluate/',
        ListeningEvaluateView.as_view(),
        name='voice-diagnostic-listening-evaluate',
    ),
    path(
        'voice-diagnostic/listening/evaluate-batch/',
        ListeningEvaluateBatchView.as_view(),
        name='voice-diagnostic-listening-evaluate-batch',
    ),
    path(
        'voice-diagnostic/speaking/evaluate/',
        SpeakingEvaluateView.as_view(),
        name='voice-diagnostic-speaking-evaluate',
    ),
    path(
        'voice-diagnostic/speaking/evaluate-batch/',
        SpeakingEvaluateBatchView.as_view(),
        name='voice-diagnostic-speaking-evaluate-batch',
    ),
    path(
        'voice-conversation/sessions/start/',
        VoiceConversationSessionStartView.as_view(),
        name='voice-conversation-session-start',
    ),
    path(
        'voice-conversation/sessions/',
        VoiceConversationSessionListView.as_view(),
        name='voice-conversation-session-list',
    ),
    path(
        'voice-conversation/sessions/<int:session_id>/',
        VoiceConversationSessionDetailView.as_view(),
        name='voice-conversation-session-detail',
    ),
    path(
        'voice-conversation/sessions/<int:session_id>/turns/',
        VoiceConversationTurnCreateView.as_view(),
        name='voice-conversation-turn-create',
    ),
    path(
        'voice-conversation/sessions/<int:session_id>/end/',
        VoiceConversationSessionEndView.as_view(),
        name='voice-conversation-session-end',
    ),
]
